Included Test Reporter

diff --git a/.github/workflows/dotnet-test.yml b/.github/workflows/dotnet-test.yml
--- a/.github/workflows/dotnet-test.yml
+++ b/.github/workflows/dotnet-test.yml
@@ -17,7 +17,16 @@ jobs:
       uses: actions/setup-dotnet@v2
       with:
         dotnet-version: 6.0.x
+
     - name: Restore dependencies
       run: dotnet restore
+      
     - name: Test
       run: dotnet test --verbosity normal
+            
+    - name: Test Report
+      uses: dorny/test-reporter@v1.5.0
+      if: success() || failure()        # run this step even if previous step failed
+      with:
+        name: test-results
+        path: jest-junit.xml
