Update dotnet-test.yml

diff --git a/.github/workflows/dotnet-test.yml b/.github/workflows/dotnet-test.yml
--- a/.github/workflows/dotnet-test.yml
+++ b/.github/workflows/dotnet-test.yml
@@ -21,3 +21,10 @@ jobs:
       run: dotnet restore
     - name: Test
       run: dotnet test --logger "trx;LogFileName=test-results.trx"
+    - name: Test Report
+      uses: dorny/test-reporter@v1
+      if: success() || failure()                          # run this step even if previous step failed
+      with:
+        name: Dotnet Tests                                # Name of the check run which will be created
+        path: 'TestResults/net6.0/*.trx'                  # Path to test results
+        reporter: dotnet-trx                              # Format of test results
